# Generated by Django 4.2.17 on 2026-01-26 20:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало смены')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец смены')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='Закрыта')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма продаж')),
                ('total_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Наличные')),
                ('total_card', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Карта')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.location', verbose_name='Локация')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.staffprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Продажа'), ('REFUND', 'Возврат'), ('ADJUSTMENT', 'Корректировка'), ('WRITEOFF', 'Списание')], default='SALE', max_length=20, verbose_name='Тип транзакции')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='Экспортировано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.product', verbose_name='Товар')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pos.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.product', verbose_name='Товар')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='pos.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Ревизия остатков',
                'verbose_name_plural': 'Ревизии остатков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Перевод')], max_length=20, verbose_name='Способ оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['shift', '-created_at'], name='pos_transac_shift_i_3c4163_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['product', '-created_at'], name='pos_transac_product_78677e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['exported_at'], name='pos_transac_exporte_82e3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['shift', 'product'], name='pos_stockco_shift_i_f663aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcount',
            unique_together={('shift', 'product')},
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['location', 'is_closed'], name='pos_shift_locatio_4600d3_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['staff', '-started_at'], name='pos_shift_staff_i_5d5efd_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_closed', False)), fields=('location',), name='unique_open_shift_per_location'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction', '-created_at'], name='pos_payment_transac_d3d0c5_idx'),
        ),
    ]
